AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation to spin off a Ubuntu Workstation which can be used via RDP in browser'
 
# 3. Define VPC
#  aws --region=eu-west-2 cloudformation create-stack --stack-name testvpc  --template-body file://createvpc.yml

Resources: 

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.10.0/24
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value:  !Join ['', ["VPC-", !Ref "AWS::StackName" ]]

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MyVPC
      CidrBlock: 10.10.10.0/24
      AvailabilityZone: "eu-west-2a"
      Tags:
      - Key: Name
        Value:  !Join ['', ["Subnet-",!Ref "AWS::StackName" ]]
Outputs:
  StackVPC:
    Description: The ID of the VPC
    Value: !Ref MyVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"
  StackSubNet:
    Description: The ID of the Subnet
    Value: !Ref MySubnet
    Export:
      Name: !Sub "${AWS::StackName}-SubnetID"      