AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation to spin off a Ubuntu Workstation which can be used via RDP in browser'

# Inputs
# 1. AMI-ID - Done
# 2. Define Security Group - Done
# 3. Attach Existing VPC - ?
# 4. Define ec2 type - Done
# 

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: Ubuntu EC2 instance type
    Type: String
    Default: t2.medium
    AllowedValues:
      - t1.micro
      - t2.micro
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: PV64
    t2.micro:
      Arch: HVM64
    t2.medium:
      Arch: HVM64      

  AWSRegionArch2AMI:
    eu-west-2:
      PV64: NOT_SUPPORTED
      HVM64: ami-0d8d7288aca78ee6f
      HVMG2: ami-0d8d7288aca78ee6f
Resources:
  UbuntuWorkStationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Ubuntu WorkStation to Enable RDP access over http
      GroupName: Ubuntu WorkStation
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0          
        - IpProtocol: tcp
          FromPort: '3389'
          ToPort: '3389'
          CidrIp: 0.0.0.0/0          
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0          

  Ubuntu:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          ubuntu_install:
            - install_cfn
        install_cfn:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Join ['', ['[main]

                    ', stack=, !Ref 'AWS::StackId', '

                    ', region=, !Ref 'AWS::Region', '

                    ']]
              mode: '000400'
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Join ['', ['[cfn-auto-reloader-hook]

                    ', 'triggers=post.update

                    ', 'path=Resources.Ubuntu.Metadata.AWS::CloudFormation::Init

                    ', 'action=/opt/aws/bin/cfn-init -v ', '         --stack ', !Ref 'AWS::StackName',
                  '         --resource Ubuntu ', '         --configsets ubuntu_install ',
                  '         --region ', !Ref 'AWS::Region', '

                    ']]
              mode: '000400'
              owner: root
              group: root
          services:
            sysvinit:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf

    Properties:
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch,
          !Ref 'InstanceType', Arch]]
      InstanceType: !Ref 'InstanceType'
      SecurityGroups:
        - !Ref 'UbuntuWorkStationSecurityGroup'

      NetworkInterfaces:
        - SubnetId: subnet-05714a2ac3ed70185

      GroupSet:
      - Ref: 'UbuntuWorkStationSecurityGroup'

      KeyName: !Ref 'KeyName'

      UserData:
       Fn::Base64: !Sub |
          #!/bin/bash 
         
          mvn --version

          sudo su
          # install yum
          # See logs at /var/log/cloud-init-output.log

          ps aux | grep -i apt 

          systemctl stop apt-daily.timer
         
          ps aux | grep -i apt 
          
          systemctl disable apt-daily.timer
          systemctl mask apt-daily.service
          systemctl daemon-reload

          killall update-notifier
           

          rm /var/lib/dpkg/lock-frontend

          rm /var/lib/dpkg/lock

          rm /var/cache/apt/archives/lock

          dpkg --configure -a
          
          apt-get update
          apt -y install yum
          apt -y install yum-utils

 
